services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy

  ai_api:
    build: ai-api
    ports:
      - "8080:8080"
    env_file:
      - ai-api/.env

  db:
    image: postgres:13
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lani" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: