services:
  backend:
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install watchdog &&
             python manage.py migrate &&
             watchmedo auto-restart --patterns='*.py' --recursive -- python manage.py runserver 0.0.0.0:8000"