services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db

  ai_api:
    build: ai-api
    ports:
      - "8080:8080"
    env_file:
      - ai-api/.env

  db:
    image: postgres:13
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: