services:
  - name: backend
    type: web
    runtime: docker
    env: docker
    repo: https://github.com/heeran-kim/promoease-backend
    branch: main
    plan: free
    dockerfilePath: backend/Dockerfile.render
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: USE_RENDER_DB
        value: "true"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,https://promoease-frontend.vercel.app,https://backend-yiuo.onrender.com"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,0.0.0.0,promoease-frontend.vercel.app,backend-yiuo.onrender.com"

  - name: ai-api
    type: web
    runtime: docker
    env: docker
    repo: https://github.com/heeran-kim/promoease-backend
    branch: main
    plan: free
    dockerfilePath: ai-api/Dockerfile.render

databases:
  - name: postgres
    plan: free