services:
  - name: backend
    type: web
    runtime: docker
    env: docker
    repo: https://github.com/heeran-kim/promoease-backend
    branch: main
    plan: free
    dockerfilePath: backend/Dockerfile.render
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - name: ai-api
    type: web
    runtime: docker
    env: docker
    repo: https://github.com/heeran-kim/promoease-backend
    branch: main
    plan: free
    dockerfilePath: ai-api/Dockerfile.render

databases:
  - name: postgres
    plan: free